# Generated by Django 4.0 on 2022-01-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='S_Reason',
            field=models.TextField(default='Checking transaction', max_length=500, null=True),
        ),
    ]
