# Generated by Django 4.0 on 2022-01-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved',
            name='S_Reason',
        ),
        migrations.AddField(
            model_name='contact',
            name='transactionstatus',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='approved',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
