# Generated by Django 4.0 on 2022-01-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_approved_s_reason_contact_transactionstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved',
            name='Paymentss',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='approved',
            name='fullthesis',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='Paymentss',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='fullthesis',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
