# Generated by Django 4.0 on 2022-01-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_approved_paymentss_approved_fullthesis_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Applications',
        ),
    ]
