# Generated by Django 4.0 on 2022-01-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_contact_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='titlethesis',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='approved',
            name='titlethesis',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
