# Generated by Django 4.0 on 2022-01-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_authenticate'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticate',
            name='sq',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
