# Generated by Django 4.0 on 2022-01-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_applications_pc_approved_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='onTime',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='ptime',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='approved',
            name='onTime',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='approved',
            name='ptime',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='approved',
            name='time',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
